package pojo;

// Generated 2013-5-13 0:41:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TLinks generated by hbm2java
 */
public class TLinks implements java.io.Serializable {

	private Integer id;
	private Short depth;
	private String anchor;
	private String url;
	private Date createTime;
	private Integer parentDocId;

	public TLinks() {
	}

	public TLinks(Short depth, Date createTime) {
		this.depth = depth;
		this.createTime = createTime;
	}

	public TLinks(Short depth, String anchor, String url, Date createTime,
			Integer parentDocId) {
		this.depth = depth;
		this.anchor = anchor;
		this.url = url;
		this.createTime = createTime;
		this.parentDocId = parentDocId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Short getDepth() {
		return this.depth;
	}

	public void setDepth(Short depth) {
		this.depth = depth;
	}

	public String getAnchor() {
		return this.anchor;
	}

	public void setAnchor(String anchor) {
		this.anchor = anchor;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getParentDocId() {
		return this.parentDocId;
	}

	public void setParentDocId(Integer parentDocId) {
		this.parentDocId = parentDocId;
	}

}
