package com.mycrawler.pojo;

// Generated 2013-5-19 23:29:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TAction generated by hbm2java
 */
public class TAction implements java.io.Serializable {

	private Integer id;
	private String baseUrl;
	private Date createTime;

	public TAction() {
	}

	public TAction(String baseUrl, Date createTime) {
		this.baseUrl = baseUrl;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBaseUrl() {
		return this.baseUrl;
	}

	public void setBaseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
