package com.mycrawler.pojo;

// Generated 2013-5-19 23:29:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TLinks generated by hbm2java
 */
public class TLink implements java.io.Serializable {

	private Integer id;
	private TSeed TSeed;
	private int depth;
	private String anchor;
	private String url;
	private Date createTime;
	private Integer docId;
	private Integer parentDocId;

	public TLink() {
	}

	public TLink(int depth) {
		this.depth = depth;
	}

	public TLink(TSeed TSeed, int depth, String anchor, String url,
			Date createTime, Integer docId, Integer parentDocId) {
		this.TSeed = TSeed;
		this.depth = depth;
		this.anchor = anchor;
		this.url = url;
		this.createTime = createTime;
		this.docId = docId;
		this.parentDocId = parentDocId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TSeed getTSeed() {
		return this.TSeed;
	}

	public void setTSeed(TSeed TSeed) {
		this.TSeed = TSeed;
	}

	public int getDepth() {
		return this.depth;
	}

	public void setDepth(int depth) {
		this.depth = depth;
	}

	public String getAnchor() {
		return this.anchor;
	}

	public void setAnchor(String anchor) {
		this.anchor = anchor;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getDocId() {
		return this.docId;
	}

	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	public Integer getParentDocId() {
		return this.parentDocId;
	}

	public void setParentDocId(Integer parentDocId) {
		this.parentDocId = parentDocId;
	}

}
