package com.mycrawler.pojo;

// Generated 2013-5-19 23:29:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TSeed generated by hbm2java
 */
public class TSeed implements java.io.Serializable {

	private Integer id;
	private String seed;
	private Date lastVisitTime;
	private Set TLinkses = new HashSet(0);

	public TSeed() {
	}

	public TSeed(String seed) {
		this.seed = seed;
	}

	public TSeed(String seed, Date lastVisitTime, Set TLinkses) {
		this.seed = seed;
		this.lastVisitTime = lastVisitTime;
		this.TLinkses = TLinkses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSeed() {
		return this.seed;
	}

	public void setSeed(String seed) {
		this.seed = seed;
	}

	public Date getLastVisitTime() {
		return this.lastVisitTime;
	}

	public void setLastVisitTime(Date lastVisitTime) {
		this.lastVisitTime = lastVisitTime;
	}

	public Set getTLinkses() {
		return this.TLinkses;
	}

	public void setTLinkses(Set TLinkses) {
		this.TLinkses = TLinkses;
	}

}
