package com.mycrawler.pojo;

// Generated 2013-5-19 23:29:56 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

/**
 * TSeed generated by hbm2java
 */
public class TSeed implements java.io.Serializable {

	private Integer id;
	private String seed; //url
	private String key; //搜索关键词
	private Date lastVisitTime;
	private List TLinkses = new ArrayList(0);

	public TSeed() {
	}

	public TSeed(String seed) {
		this.seed = seed;
	}

	public TSeed(String seed, Date lastVisitTime, List TLinkses) {
		this.seed = seed;
		this.lastVisitTime = lastVisitTime;
		this.TLinkses = TLinkses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSeed() {
		return this.seed;
	}

	public void setSeed(String seed) {
		this.seed = seed;
	}

	public Date getLastVisitTime() {
		return this.lastVisitTime;
	}

	public void setLastVisitTime(Date lastVisitTime) {
		this.lastVisitTime = lastVisitTime;
	}

	public List getTLinkses() {
		return this.TLinkses;
	}

	public void setTLinkses(List TLinkses) {
		this.TLinkses = TLinkses;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

}
